### ISSUE TITLE
Can't use accesses + middlewares

### ISSUE THREAD

**Issue by SakiiR** [ysocorp/koa-smart#3]
My middleware is never called if the accesses fail.

The accesses are checked before the middlewares.

It should be the inverse, so that we could populate the `ctx.state` before going into the accesses.

**Comment by jeanclaudeyalap** [comment]
@SakiiR , yes this is the behaviour, because in my implementation (my thinking), the `middleware` to add user informations (to know the access) should be add at the begining of your app (with the `app.addMiddleware` function).
And middlewares of a route, is only to do job outside of the accesses scope, so you can be sure that you have the right access to execute the code of the middleware.
